apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: ngnix-replicaset
spec:
  replicas: 3
  selector: 
    matchLabels:
      app: ngnix
  template:
    metadata:
      labels:
        app: ngnix
      spec:
        containers:
        - name: ngnix
          image: ngnix:latest
          ports:
          - containerPort: 80